openapi: 3.0.0
info:
  title: verifaid
  version: '1.0'
  contact:
    name: jagruti
    email: jagruti@wohlig.com
  description: 'Secured Public API'
tags: ['user']
servers:
  - url: 'http://localhost:3000'
    description: Verifying money flow across businesses.
paths:
  /:
    post:
      summary: Your POST endpoint
      description: Check Provided information of user is Valid or not.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  companyName:
                    type: object
                    properties:
                      status:
                        type: boolean
                  companyHouseNumber:
                    type: object
                    properties:
                      status:
                        type: boolean
                  firstName:
                    type: object
                    properties:
                      status:
                        type: boolean
                  lastName:
                    type: object
                    properties:
                      status:
                        type: boolean
                  email:
                    type: object
                    properties:
                      status:
                        type: boolean
                  phone:
                    type: object
                    properties:
                      status:
                        type: boolean
                  addressOne:
                    type: object
                    properties:
                      status:
                        type: boolean
                  addressTwo:
                    type: object
                    properties:
                      status:
                        type: boolean
                  postCode:
                    type: object
                    properties:
                      status:
                        type: boolean
                  houseNumber:
                    type: object
                    properties:
                      status:
                        type: boolean
                  country:
                    type: object
                    properties:
                      status:
                        type: boolean
                  bankName:
                    type: object
                    properties:
                      status:
                        type: boolean
                  accountNumber:
                    type: object
                    properties:
                      status:
                        type: boolean
                  vatNumber:
                    type: object
                    properties:
                      status:
                        type: boolean
                  dob:
                    type: object
                    properties:
                      status:
                        type: boolean
                  sortCode:
                    type: object
                    properties:
                      status:
                        type: boolean
        '401':
          description: Unauthorized
        '404':
          description: A user with the specified Information was not found.
      operationId: post-userDetails-getInfo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                companyName:
                  type: string
                companyHouseNumber:
                  type: string
                firstName:
                  type: string
                lastName':
                  type: string
                email:
                  type: string
                phone:
                  type: string
                addressOne:
                  type: string
                addressTwo:
                  type: string
                postalCode:
                  type: string
                houseNumber:
                  type: string
                country:
                  type: string
                bankName:
                  type: string
                accountNumber:
                  type: string
                vatNumber:
                  type: string
                dob:
                  type: string
                sortCode:
                  type: string
      parameters:
        - schema:
            type: string
          in: header
          name: accesstoken
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        companyName:
          type: object
          properties:
            status:
              type: boolean
        companyHouseNumber:
          type: object
          properties:
            status:
              type: boolean
        firstName:
          type: object
          properties:
            status:
              type: boolean
        lastName:
          type: object
          properties:
            status:
              type: boolean
        email:
          type: object
          properties:
            status:
              type: boolean
        phone:
          type: object
          properties:
            status:
              type: boolean
        addressOne:
          type: object
          properties:
            status:
              type: boolean
        addressTwo:
          type: object
          properties:
            status:
              type: boolean
        postCode:
          type: object
          properties:
            status:
              type: boolean
        houseNumber:
          type: object
          properties:
            status:
              type: boolean
        country:
          type: object
          properties:
            status:
              type: boolean
        bankName:
          type: object
          properties:
            status:
              type: boolean
        accountNumber:
          type: object
          properties:
            status:
              type: boolean
        vatNumber:
          type: object
          properties:
            status:
              type: boolean
        dob:
          type: object
          properties:
            status:
              type: boolean
        sortCode:
          type: object
          properties:
            status:
              type: boolean
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
